org: shilomagen
app: slots-finder
service: slots-finder

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  timeout: 60

functions:
  slotsFinder:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-plugin-typescript
  - serverless-offline
