org: shilomagen
app: slots-finder
service: slots-finder

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  timeout: 120

constructs:
  slotsQueue:
    type: queue
    worker:
      handler: handler.setAppointments
      timeout: 120

functions:
  slotsFinder:
    handler: handler.findSlots
    events:
      # Invoke Lambda function every minute
      - schedule: rate(2 minute)
    environment:
      QUEUE_URL: ${construct:slotsQueue.queueUrl}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-lift
