org: shilomagen
app: slots-finder
service: slots-finder

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)

plugins:
  - serverless-plugin-typescript
